import { ReactNode } from 'react'

type Language = {
  code: string
  name: string
  flag: ReactNode
}

const baseLanguages: Language[] = [
  { code: 'af', name: 'Afrikaans', flag: '🇿🇦' },
  { code: 'am', name: 'Amharic', flag: '🇪🇹' },
  { code: 'ar', name: 'Arabic', flag: '🇸🇦' },
  { code: 'as', name: 'Assamese', flag: '🇮🇳' },
  { code: 'az', name: 'Azerbaijani', flag: '🇦🇿' },
  { code: 'ba', name: 'Bashkir', flag: '🇷🇺' },
  { code: 'be', name: 'Belarusian', flag: '🇧🇾' },
  { code: 'bg', name: 'Bulgarian', flag: '🇧🇬' },
  { code: 'bn', name: 'Bengali', flag: '🇧🇩' },
  { code: 'bo', name: 'Tibetan', flag: '🇹🇳' },
  { code: 'br', name: 'Breton', flag: '🇫🇷' },
  { code: 'bs', name: 'Bosnian', flag: '🇧🇦' },
  { code: 'ca', name: 'Catalan', flag: '🇪🇸' },
  { code: 'cs', name: 'Czech', flag: '🇨🇿' },
  { code: 'cy', name: 'Welsh', flag: '🇼🇱' },
  { code: 'da', name: 'Danish', flag: '🇩🇰' },
  { code: 'de', name: 'German', flag: '🇩🇪' },
  { code: 'el', name: 'Greek', flag: '🇬🇷' },
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'es', name: 'Spanish', flag: '🇪🇸' },
  { code: 'et', name: 'Estonian', flag: '🇪🇪' },
  { code: 'eu', name: 'Basque', flag: '🇪🇺' },
  { code: 'fa', name: 'Persian', flag: '🇮🇷' },
  { code: 'fi', name: 'Finnish', flag: '🇫🇮' },
  { code: 'fo', name: 'Faroese', flag: '🇫🇴' },
  { code: 'fr', name: 'French', flag: '🇫🇷' },
  { code: 'gl', name: 'Galician', flag: '🇪🇸' },
  { code: 'gu', name: 'Gujarati', flag: '🇮🇳' },
  { code: 'ha', name: 'Hausa', flag: '🇳🇬' },
  { code: 'haw', name: 'Hawaiian', flag: '🇺🇸' },
  { code: 'he', name: 'Hebrew', flag: '🇮🇱' },
  { code: 'hi', name: 'Hindi', flag: '🇮🇳' },
  { code: 'hr', name: 'Croatian', flag: '🇭🇷' },
  { code: 'ht', name: 'Haitian Creole', flag: '🇭🇹' },
  { code: 'hu', name: 'Hungarian', flag: '🇭🇺' },
  { code: 'hy', name: 'Armenian', flag: '🇦🇲' },
  { code: 'id', name: 'Indonesian', flag: '🇮🇩' },
  { code: 'is', name: 'Icelandic', flag: '🇮🇸' },
  { code: 'it', name: 'Italian', flag: '🇮🇹' },
  { code: 'ja', name: 'Japanese', flag: '🇯🇵' },
  { code: 'jw', name: 'Javanese', flag: '🇮🇩' },
  { code: 'ka', name: 'Georgian', flag: '🇬🇪' },
  { code: 'kk', name: 'Kazakh', flag: '🇰🇿' },
  { code: 'km', name: 'Khmer', flag: '🇰🇭' },
  { code: 'kn', name: 'Kannada', flag: '🇮🇳' },
  { code: 'ko', name: 'Korean', flag: '🇰🇷' },
  { code: 'la', name: 'Latin', flag: '🇱🇦' },
  { code: 'lb', name: 'Luxembourgish', flag: '🇱🇺' },
  { code: 'ln', name: 'Lingala', flag: '🇨🇩' },
  { code: 'lo', name: 'Lao', flag: '🇱🇦' },
  { code: 'lt', name: 'Lithuanian', flag: '🇱🇹' },
  { code: 'lv', name: 'Latvian', flag: '🇱🇻' },
  { code: 'mg', name: 'Malagasy', flag: '🇲🇬' },
  { code: 'mi', name: 'Māori', flag: '🇳🇿' },
  { code: 'mk', name: 'Macedonian', flag: '🇲🇰' },
  { code: 'ml', name: 'Malayalam', flag: '🇮🇳' },
  { code: 'mn', name: 'Mongolian', flag: '🇲🇳' },
  { code: 'mr', name: 'Marathi', flag: '🇮🇳' },
  { code: 'ms', name: 'Malay', flag: '🇲🇾' },
  { code: 'mt', name: 'Maltese', flag: '🇲🇹' },
  { code: 'my', name: 'Burmese', flag: '🇲🇲' },
  { code: 'ne', name: 'Nepali', flag: '🇳🇵' },
  { code: 'nl', name: 'Dutch', flag: '🇳🇱' },
  { code: 'nn', name: 'Norwegian Nynorsk', flag: '🇳🇴' },
  { code: 'no', name: 'Norwegian', flag: '🇳🇴' },
  { code: 'oc', name: 'Occitan', flag: '🇫🇷' },
  { code: 'pa', name: 'Punjabi', flag: '🇮🇳' },
  { code: 'pl', name: 'Polish', flag: '🇵🇱' },
  { code: 'ps', name: 'Pashto', flag: '🇦🇫' },
  { code: 'pt', name: 'Portuguese', flag: '🇵🇹' },
  { code: 'ro', name: 'Romanian', flag: '🇷🇴' },
  { code: 'ru', name: 'Russian', flag: '🇷🇺' },
  { code: 'sa', name: 'Sanskrit', flag: '🇮🇳' },
  { code: 'sd', name: 'Sindhi', flag: '🇵🇰' },
  { code: 'si', name: 'Sinhala', flag: '🇱🇰' },
  { code: 'sk', name: 'Slovak', flag: '🇸🇰' },
  { code: 'sl', name: 'Slovenian', flag: '🇸🇮' },
  { code: 'sn', name: 'Shona', flag: '🇿🇼' },
  { code: 'so', name: 'Somali', flag: '🇸🇴' },
  { code: 'sq', name: 'Albanian', flag: '🇦🇱' },
  { code: 'sr', name: 'Serbian', flag: '🇷🇸' },
  { code: 'su', name: 'Sundanese', flag: '🇮🇩' },
  { code: 'sv', name: 'Swedish', flag: '🇸🇪' },
  { code: 'sw', name: 'Swahili', flag: '🇹🇿' },
  { code: 'ta', name: 'Tamil', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', flag: '🇮🇳' },
  { code: 'tg', name: 'Tajik', flag: '🇹🇯' },
  { code: 'th', name: 'Thai', flag: '🇹🇭' },
  { code: 'tk', name: 'Turkmen', flag: '🇹🇲' },
  { code: 'tl', name: 'Filipino', flag: '🇵🇭' },
  { code: 'tr', name: 'Turkish', flag: '🇹🇷' },
  { code: 'tt', name: 'Tatar', flag: '🇷🇺' },
  { code: 'uk', name: 'Ukrainian', flag: '🇺🇦' },
  { code: 'ur', name: 'Urdu', flag: '🇵🇰' },
  { code: 'uz', name: 'Uzbek', flag: '🇺🇿' },
  { code: 'vi', name: 'Vietnamese', flag: '🇻🇳' },
  { code: 'yi', name: 'Yiddish', flag: '🇮🇱' },
  { code: 'yo', name: 'Yoruba', flag: '🇳🇬' },
  { code: 'zh', name: 'Chinese', flag: '🇨🇳' },
  { code: 'yue', name: 'Cantonese', flag: '🇭🇰' },
]

export const LANGUAGES: Language[] = [
  { code: 'auto', name: 'Auto', flag: '🌐' },
  ...baseLanguages.sort((a, b) => a.name.localeCompare(b.name)),
]
