type Language = {
  code: string
  name: string
  country?: string
}

const baseLanguages: Language[] = [
  { code: 'af', name: 'Afrikaans', country: 'za' },
  { code: 'am', name: 'Amharic', country: 'et' },
  { code: 'ar', name: 'Arabic', country: 'sa' },
  { code: 'as', name: 'Assamese', country: 'in' },
  { code: 'az', name: 'Azerbaijani', country: 'az' },
  { code: 'ba', name: 'Bashkir', country: 'ru' },
  { code: 'be', name: 'Belarusian', country: 'by' },
  { code: 'bg', name: 'Bulgarian', country: 'bg' },
  { code: 'bn', name: 'Bengali', country: 'bd' },
  { code: 'bo', name: 'Tibetan', country: 'cn' },
  { code: 'br', name: 'Breton', country: 'fr' },
  { code: 'bs', name: 'Bosnian', country: 'ba' },
  { code: 'ca', name: 'Catalan', country: 'es' },
  { code: 'cs', name: 'Czech', country: 'cz' },
  { code: 'cy', name: 'Welsh', country: 'gb' },
  { code: 'da', name: 'Danish', country: 'dk' },
  { code: 'de', name: 'German', country: 'de' },
  { code: 'el', name: 'Greek', country: 'gr' },
  { code: 'en', name: 'English', country: 'gb' },
  { code: 'es', name: 'Spanish', country: 'es' },
  { code: 'et', name: 'Estonian', country: 'ee' },
  { code: 'eu', name: 'Basque', country: 'es' },
  { code: 'fa', name: 'Persian', country: 'ir' },
  { code: 'fi', name: 'Finnish', country: 'fi' },
  { code: 'fo', name: 'Faroese', country: 'fo' },
  { code: 'fr', name: 'French', country: 'fr' },
  { code: 'gl', name: 'Galician', country: 'es' },
  { code: 'gu', name: 'Gujarati', country: 'in' },
  { code: 'ha', name: 'Hausa', country: 'ng' },
  { code: 'haw', name: 'Hawaiian', country: 'us' },
  { code: 'he', name: 'Hebrew', country: 'ps' },
  { code: 'hi', name: 'Hindi', country: 'in' },
  { code: 'hr', name: 'Croatian', country: 'hr' },
  { code: 'ht', name: 'Haitian Creole', country: 'ht' },
  { code: 'hu', name: 'Hungarian', country: 'hu' },
  { code: 'hy', name: 'Armenian', country: 'am' },
  { code: 'id', name: 'Indonesian', country: 'id' },
  { code: 'is', name: 'Icelandic', country: 'is' },
  { code: 'it', name: 'Italian', country: 'it' },
  { code: 'ja', name: 'Japanese', country: 'jp' },
  { code: 'jw', name: 'Javanese', country: 'id' },
  { code: 'ka', name: 'Georgian', country: 'ge' },
  { code: 'kk', name: 'Kazakh', country: 'kz' },
  { code: 'km', name: 'Khmer', country: 'kh' },
  { code: 'kn', name: 'Kannada', country: 'in' },
  { code: 'ko', name: 'Korean', country: 'kr' },
  { code: 'la', name: 'Latin', country: 'va' },
  { code: 'lb', name: 'Luxembourgish', country: 'lu' },
  { code: 'ln', name: 'Lingala', country: 'cd' },
  { code: 'lo', name: 'Lao', country: 'la' },
  { code: 'lt', name: 'Lithuanian', country: 'lt' },
  { code: 'lv', name: 'Latvian', country: 'lv' },
  { code: 'mg', name: 'Malagasy', country: 'mg' },
  { code: 'mi', name: 'Māori', country: 'nz' },
  { code: 'mk', name: 'Macedonian', country: 'mk' },
  { code: 'ml', name: 'Malayalam', country: 'in' },
  { code: 'mn', name: 'Mongolian', country: 'mn' },
  { code: 'mr', name: 'Marathi', country: 'in' },
  { code: 'ms', name: 'Malay', country: 'my' },
  { code: 'mt', name: 'Maltese', country: 'mt' },
  { code: 'my', name: 'Burmese', country: 'mm' },
  { code: 'ne', name: 'Nepali', country: 'np' },
  { code: 'nl', name: 'Dutch', country: 'nl' },
  { code: 'nn', name: 'Norwegian Nynorsk', country: 'no' },
  { code: 'no', name: 'Norwegian', country: 'no' },
  { code: 'oc', name: 'Occitan', country: 'fr' },
  { code: 'pa', name: 'Punjabi', country: 'in' },
  { code: 'pl', name: 'Polish', country: 'pl' },
  { code: 'ps', name: 'Pashto', country: 'af' },
  { code: 'pt', name: 'Portuguese', country: 'pt' },
  { code: 'ro', name: 'Romanian', country: 'ro' },
  { code: 'ru', name: 'Russian', country: 'ru' },
  { code: 'sa', name: 'Sanskrit', country: 'in' },
  { code: 'sd', name: 'Sindhi', country: 'pk' },
  { code: 'si', name: 'Sinhala', country: 'lk' },
  { code: 'sk', name: 'Slovak', country: 'sk' },
  { code: 'sl', name: 'Slovenian', country: 'si' },
  { code: 'sn', name: 'Shona', country: 'zw' },
  { code: 'so', name: 'Somali', country: 'so' },
  { code: 'sq', name: 'Albanian', country: 'al' },
  { code: 'sr', name: 'Serbian', country: 'rs' },
  { code: 'su', name: 'Sundanese', country: 'id' },
  { code: 'sv', name: 'Swedish', country: 'se' },
  { code: 'sw', name: 'Swahili', country: 'tz' },
  { code: 'ta', name: 'Tamil', country: 'in' },
  { code: 'te', name: 'Telugu', country: 'in' },
  { code: 'tg', name: 'Tajik', country: 'tj' },
  { code: 'th', name: 'Thai', country: 'th' },
  { code: 'tk', name: 'Turkmen', country: 'tm' },
  { code: 'tl', name: 'Filipino', country: 'ph' },
  { code: 'tr', name: 'Turkish', country: 'tr' },
  { code: 'tt', name: 'Tatar', country: 'ru' },
  { code: 'uk', name: 'Ukrainian', country: 'ua' },
  { code: 'ur', name: 'Urdu', country: 'pk' },
  { code: 'uz', name: 'Uzbek', country: 'uz' },
  { code: 'vi', name: 'Vietnamese', country: 'vn' },
  { code: 'yo', name: 'Yoruba', country: 'ng' },
  { code: 'zh', name: 'Chinese', country: 'cn' },
  { code: 'yue', name: 'Cantonese', country: 'hk' },
]

export const LANGUAGES: Language[] = [
  { code: 'auto', name: 'Auto' },
  ...baseLanguages.sort((a, b) => a.name.localeCompare(b.name)),
]
